/**
 * The gateway entry point: the request lifecycle from a normalized request to a
 * normalized wire stream.
 *
 *   scopeKey → cache lookup (exact → semantic) → on HIT replay (free) ;
 *                                                 on MISS pick provider, stream,
 *                                                 then cache the exchange.
 *
 * What's here at scaffold: the lifecycle, Tier-1 exact caching, optional Tier-2
 * semantic (off by default until the P2 guard), and the mock/live provider
 * stream. Routing (P4), the rerank guard (P2), observability + real $ cost (P3),
 * and pre-first-token failover (P4) slot into the marked points without
 * reshaping this flow.
 */
import { scopeKey, lastUserQuery } from "./scopeKey";
import { routeModel } from "./router";
import { embed } from "./embed";
import { lookup, put } from "./cache";
import { isHit } from "./types";
import { providerChain } from "./providers";
import { establishStream } from "./resilience";
import { deterministicReject, llmJudgeGuard, judgeAvailable } from "./rerank";
import { costUsd } from "./pricing";
import { record } from "./observe";
import type { GatewayRequest, GuardVerdict, ProviderEvent, Usage, WireEvent } from "./types";

const DEFAULT_THRESHOLD = Number(process.env.CACHE_THRESHOLD ?? "0.92");

export async function* runGateway(
  req: GatewayRequest,
  signal?: AbortSignal,
): AsyncGenerator<WireEvent> {
  const start = Date.now();

  // Optional routing (off by default): pick the model before the scope key, since
  // the model is part of the key. A no-op unless GATEWAY_ROUTING=on.
  const routed = routeModel(req, lastUserQuery(req.messages));
  if (routed !== req.model) req = { ...req, model: routed };

  const key = scopeKey(req);

  // Tier-2 ships OFF until the P2 rerank guard can vouch for intent — a fast,
  // wrong cached answer is worse than a slow, right one.
  const semantic = process.env.SEMANTIC_CACHE === "on" && req.cache?.mode !== "off";
  const threshold = req.cache?.threshold ?? DEFAULT_THRESHOLD;
  const judgeOn = process.env.GUARD_JUDGE === "on" && judgeAvailable();

  // When the guard turns a high-similarity candidate into a miss, we remember
  // which tier blocked it and the cosine it scored — the project's thesis made
  // visible (a hit a fixed threshold would have served, correctly refused).
  let guardVerdict: GuardVerdict | null = null;

  // Tier-1 exact first — it needs no embedding, so an exact hit never pays for an
  // OpenAI embedding call. Only embed when the exact tier misses and Tier-2 is on.
  let result = lookup(key, { embedding: null, threshold, semantic: false });
  let queryEmbedding: number[] | null = null;
  if (!isHit(result) && semantic) {
    queryEmbedding = await embed(key.query);
    result = lookup(key, {
      embedding: queryEmbedding,
      threshold,
      semantic: true,
      // Tier-A guard (synchronous, keyless): reject confident polarity/scope flips.
      guard: (probeQuery, candidate) => !deterministicReject(probeQuery, candidate.query),
    });
    // Tier-A blocked the top candidate ⇒ record the deterministic catch.
    if (!isHit(result) && result.rejected) {
      guardVerdict = {
        by: "deterministic",
        similarity: result.rejected.similarity,
        candidate: result.rejected.candidate.query,
      };
    }
  }

  // Tier-B guard: an async LLM judge confirms a *semantic* hit's intent. Off
  // unless GUARD_JUDGE=on and a key is present; an exact hit never needs it.
  let hit = isHit(result) ? result : null;
  if (hit && hit.tier === "semantic" && judgeOn) {
    const keep = await llmJudgeGuard(key.query, hit.entry.query);
    if (!keep) {
      guardVerdict = { by: "judge", similarity: hit.similarity, candidate: hit.entry.query };
      hit = null; // judge rejected → treat as a miss
    }
  }

  // ── Cache HIT: replay the stored exchange, no provider spend ───────────────
  if (hit) {
    const { entry, tier, similarity } = hit;
    // The cached answer was generated by whichever model the entry's `done`
    // recorded — price the SAVINGS against that, not the requested model.
    const doneEv = entry.events.find((e) => e.type === "done");
    const servedModel = doneEv?.type === "done" ? doneEv.model : entry.key.model;
    const savedUsd = costUsd(servedModel, entry.usage);

    yield { type: "meta", cache: tier, similarity, model: servedModel, provider: entry.provider };
    for (const ev of entry.events) {
      if (ev.type === "first_token") yield { type: "first_token", at: Date.now() };
      else if (ev.type === "text") yield { type: "text", text: ev.text };
    }
    const totalMs = Date.now() - start;
    yield { type: "done", model: servedModel, usage: entry.usage, cached: true, ttftMs: 0, totalMs, costUsd: 0 };
    record({
      "gen_ai.system": entry.provider,
      "gen_ai.request.model": req.model,
      "gen_ai.response.model": servedModel,
      "gen_ai.usage.input_tokens": entry.usage?.inputTokens,
      "gen_ai.usage.output_tokens": entry.usage?.outputTokens,
      "veritas.cache.tier": tier,
      "veritas.cache.similarity": similarity,
      "veritas.cache.dollars_saved": savedUsd,
      "veritas.latency.ttft_ms": 0,
      "veritas.latency.total_ms": totalMs,
      "veritas.cost.dollars": 0, // a cache hit is free — the whole point
    });
    return;
  }

  // ── Cache MISS: stream from the provider chain, with pre-first-token failover ─
  let committed;
  try {
    committed = await establishStream(providerChain(), req, signal);
  } catch (err) {
    if (err instanceof Error && err.name === "AbortError") return;
    yield { type: "error", message: err instanceof Error ? err.message : "gateway error" };
    return;
  }
  if (!committed) {
    yield { type: "error", message: "all providers unavailable" };
    return;
  }
  const { provider, model, gen, first, rescued } = committed;
  yield {
    type: "meta",
    cache: "miss",
    model,
    provider: provider.name,
    ...(guardVerdict ? { guard: guardVerdict } : {}),
    ...(rescued ? { rescued: true } : {}),
  };

  const collected: ProviderEvent[] = [];
  let usage: Usage | undefined;
  let firstAt: number | undefined;
  let completed = false;

  // The first event was already pulled — that's the commitment point. Handle it,
  // then drain the rest. A post-first-token error is the honest wall (partial +
  // error), because once headers are on the wire clean failover is impossible.
  collected.push(first);
  if (first.type === "first_token") {
    firstAt = first.at;
    yield { type: "first_token", at: first.at };
  } else if (first.type === "text") {
    yield { type: "text", text: first.text };
  } else if (first.type === "done") {
    usage = first.usage;
    completed = true;
  }
  try {
    for await (const ev of gen) {
      collected.push(ev);
      if (ev.type === "first_token") {
        firstAt = ev.at;
        yield { type: "first_token", at: ev.at };
      } else if (ev.type === "text") {
        yield { type: "text", text: ev.text };
      } else if (ev.type === "done") {
        usage = ev.usage;
        completed = true;
      }
    }
  } catch (err) {
    if (err instanceof Error && err.name === "AbortError") return;
    yield {
      type: "error",
      message: `stream interrupted after first token (no clean failover once headers commit): ${
        err instanceof Error ? err.message : "error"
      }`,
    };
    return;
  }

  // Only cache a fully-completed exchange.
  if (!completed) {
    yield { type: "error", message: "provider stream ended prematurely" };
    return;
  }

  put(key, provider.name, queryEmbedding, collected, usage);

  const totalMs = Date.now() - start;
  const ttftMs = firstAt ? firstAt - start : undefined;
  const spentUsd = costUsd(model, usage);
  yield { type: "done", model, usage, cached: false, ttftMs, totalMs, costUsd: spentUsd };
  record({
    "gen_ai.system": provider.name,
    "gen_ai.request.model": req.model,
    "gen_ai.response.model": model,
    "gen_ai.usage.input_tokens": usage?.inputTokens,
    "gen_ai.usage.output_tokens": usage?.outputTokens,
    "veritas.cache.tier": "miss",
    "veritas.latency.ttft_ms": ttftMs,
    "veritas.latency.total_ms": totalMs,
    "veritas.cost.dollars": spentUsd,
    "veritas.resilience.rescued": rescued,
    "veritas.guard.blocked": guardVerdict ? true : undefined,
  });
}

export type { GatewayRequest, WireEvent } from "./types";
